[env]
VC_BUILD_DIR = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
DEST_PATH = "YOUR_PATH\\build"
TARGET_CLIENT_PATH = "YOUR_PATH\\user"
TARGET_CLIENT_RE_PATH = "YOUR_PATH\\user\\target\\release\\user.exe"

[env.development]
TARGET_PATH = "target/debug"

[env.production]
TARGET_PATH = "target/release"
BUILD_RELEASE = "--release"

[tasks.build-driver]
script = '''
cargo build %BUILD_FLAGS%
'''

[tasks.build-client]
script = '''
cd %TARGET_CLIENT_PATH%
cargo build --release
copy %TARGET_CLIENT_RE_PATH% %DEST_PATH%
'''

[tasks.rename]
ignore_errors = true
script = '''
cd %TARGET_PATH%
rename driver.dll driver.sys
copy driver.sys %DEST_PATH%
'''

[tasks.sign]
dependencies = ["build-driver", "rename","build-client" ]
script = '''
call "%VC_BUILD_DIR%"
if not exist DriverCertificate.cer ( makecert -r -pe -ss PrivateCertStore -n CN=DriverCertificate DriverCertificate.cer ) else ( echo Certificate already exists. )
signtool sign /a /v /s PrivateCertStore /n DriverCertificate /fd certHash /t http://timestamp.digicert.com %TARGET_PATH%/driver.sys


'''
